### ISSUE TITLE
panic: runtime error: index out of range in tdigest.CentroidList.Less(...)

### ISSUE THREAD

**Issue by Dieterbe** [influxdata/tdigest#14]
Hello,
seeing panics like below. I have not been able to reliably reproduce yet. sometimes it seems to work, sometimes not.
Basically my code creates a tdigest like so `td := tdigest.NewWithCompression(100)`
and then calls this a bunch of times : `td.Add(s, 1)` where s is some time.Duration converted to a float64 (typically a few millisecods)

any ideas? thanks.
```
panic: runtime error: index out of range

goroutine 1998768 [running]:
github.com/influxdata/tdigest.CentroidList.Less(...)
	/home/dieter/go/src/github.com/influxdata/tdigest/centroid.go:51
sort.doPivot(0xb3d600, 0xc0a257f4b0, 0xce, 0x10a, 0xc, 0x10b)
	/usr/lib/go/src/sort/sort.go:121 +0x502
sort.quickSort(0xb3d600, 0xc0a257f4b0, 0xce, 0x10a, 0x11)
	/usr/lib/go/src/sort/sort.go:190 +0x9a
sort.quickSort(0xb3d600, 0xc0a257f4b0, 0xce, 0x250, 0x13)
	/usr/lib/go/src/sort/sort.go:194 +0xf8
sort.Sort(0xb3d600, 0xc0a257f4b0)
	/usr/lib/go/src/sort/sort.go:218 +0x79
github.com/influxdata/tdigest.(*TDigest).process(0xc0a257f480)
	/home/dieter/go/src/github.com/influxdata/tdigest/tdigest.go:77 +0xdf
github.com/influxdata/tdigest.(*TDigest).AddCentroid(0xc0a257f480, 0x40a6c20000000000, 0x3ff0000000000000)
	/home/dieter/go/src/github.com/influxdata/tdigest/tdigest.go:67 +0x80
github.com/influxdata/tdigest.(*TDigest).Add(...)
	/home/dieter/go/src/github.com/influxdata/tdigest/tdigest.go:42
github.com/tsenart/vegeta/lib.(*tdigestEstimator).Add(0xc003efe168, 0x40a6c20000000000)
```

**Comment by Dieterbe** [comment]
from the same code i also get panics like so:
```
panic: runtime error: index out of range

goroutine 1980056 [running]:
github.com/influxdata/tdigest.(*TDigest).updateCumulative(0xc0ba9d3780)
	/home/dieter/go/src/github.com/influxdata/tdigest/tdigest.go:111 +0xf6
github.com/influxdata/tdigest.(*TDigest).process(0xc0ba9d3780)
	/home/dieter/go/src/github.com/influxdata/tdigest/tdigest.go:101 +0x2b0
github.com/influxdata/tdigest.(*TDigest).AddCentroid(0xc0ba9d3780, 0x40c1180000000000, 0x3ff0000000000000)
	/home/dieter/go/src/github.com/influxdata/tdigest/tdigest.go:67 +0x80
github.com/influxdata/tdigest.(*TDigest).Add(...)
	/home/dieter/go/src/github.com/influxdata/tdigest/tdigest.go:42
```

**Comment by Dieterbe** [comment]
my bad. i was accessing the tdigest unsafely.
